export const WGETORDERLISTERR = 'WGETORDERLISTERR'
export type WGETORDERLISTERR = typeof WGETORDERLISTERR

export const WGETORDERLIST = 'WGETORDERLIST'
export type WGETORDERLIST = typeof WGETORDERLIST

export const WGETORDERLISTSUC = 'WGETORDERLISTSUC'
export type WGETORDERLISTSUC = typeof WGETORDERLISTSUC


export const WORDEREDIT = 'WORDEREDIT'
export type WORDEREDIT = typeof WORDEREDIT

export const WORDEREDITSUC = 'WORDEREDITSUC'
export type WORDEREDITSUC = typeof WORDEREDITSUC

export const WORDEREDITERR = 'WORDEREDITERR'
export type WORDEREDITERR = typeof WORDEREDITERR


export const WORDERADD = 'WORDERADD'
export type WORDERADD = typeof WORDERADD

export const WORDERADDSUC = 'WORDERADDSUC'
export type WORDERADDSUC = typeof WORDERADDSUC





