export const WGETCUSLISTERR = 'WGETCUSLISTERR'
export type WGETCUSLISTERR = typeof WGETCUSLISTERR

export const WGETCUSLIST = 'WGETCUSLIST'
export type WGETCUSLIST = typeof WGETCUSLIST

export const WGETCUSLISTSUC = 'WGETCUSLISTSUC'
export type WGETCUSLISTSUC = typeof WGETCUSLISTSUC

export const WGETCUSCATESUC = 'WGETCUSCATESUC'
export type WGETCUSCATESUC = typeof WGETCUSCATESUC
