export const SCUSORDERADD = 'SCUSORDERADD'
export type SCUSORDERADD = typeof SCUSORDERADD

export const SORDERADDSUC = 'SORDERADDSUC'
export type SORDERADDSUC = typeof SORDERADDSUC

export const SORDERADDERR = 'SORDERADDERR'
export type SORDERADDERR = typeof SORDERADDERR

export const CUSOREDEREDIT = 'CUSOREDEREDIT'
export type CUSOREDEREDIT = typeof CUSOREDEREDIT

export const SORDEREDITSUC = 'SORDEREDITSUC'
export type SORDEREDITSUC = typeof SORDEREDITSUC

export const SORDEREDITERR = 'SORDEREDITERR'
export type SORDEREDITERR = typeof SORDEREDITERR

export const RESET = 'RESET'
export type RESET = typeof RESET

