export const WGETCUSCATELISTERR = 'WGETCUSCATELISTERR'
export type WGETCUSCATELISTERR = typeof WGETCUSCATELISTERR

export const WGETCUSCATELIST = 'WGETCUSCATELIST'
export type WGETCUSCATELIST = typeof WGETCUSCATELIST

export const WGETCUSCATELISTSUC = 'WGETCUSCATELISTSUC'
export type WGETCUSCATELISTSUC = typeof WGETCUSCATELISTSUC
